title       = "timus"
baseURL     = "https://timus-cli.tamnd.com/"
description = "A command line for timus."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/timus-cli"
